name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all

    - id: get-members
      uses: garnertb/get-team-members@v1
      with:
        org: garnertb-io
        team_slug: ops
        role: maintainer
        token: ${{ secrets.GITHUB_TOKEN }}
  # print results
    - run: "echo ${{ steps.get-members.outputs.members }}"
      shell: bash
